Repository DecodersCommunity/animepedia, pull requests merged in 2022-09, with the labels that each got.

#1 Update README.md
  README.md
Labels: typo

#3 Added character Uchiha Madara
  images/madara.jpg
  index.html
Labels: Awsome, good first issue, hacktoberfest, hacktoberfest-accepted

#6 Updated README.md
  README.md
Labels: hacktoberfest-accepted

#7 Added Light Yagami card
  images/download.jpg
  index.html
Labels: hacktoberfest-accepted
