Repository DecodersCommunity/animepedia, pull requests merged in 2022-10, with the labels that each got.

#12 Added L Lawliet card
  images/L(DN).png
  images/vegeta2.jpg
  index.html
Labels: hacktoberfest-accepted

#13 Added One Punch Man
  images/opm.png
  index.html
Labels: hacktoberfest-accepted

#21 Added Lelouch Lamperouge Card
  images/lelouch-lamperouge.jpg
  images/moon.png
  images/sun.png
  index.html
Labels: hacktoberfest-accepted

#22 Added accelerator
  images/accelerator.jpg
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#24 Sasuke Uchiha
  images/sasuke_uchiha.jpg
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#26 Added Tyson card
  images/tyson.jpg
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#27 Added Uchiha Obito
  images/obito.jpg
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#30 Fixed & Formatted index.html
  images/itachi.jpg
  images/roronoa zoro.jpg
  images/roronoa_zoro.jpg
  index.html
Labels: hacktoberfest-accepted

#29 Senku Ishigami added
  images/senku_ishigami.jpg
  index.html
Labels: hacktoberfest-accepted

#33 Added Endou Mamoru Card
  images/Endou.png
  index.html
Labels: hacktoberfest-accepted

#28 Edward Newgate
  images/whitebeard.jpg
  index.html
Labels: hacktoberfest-accepted

#36 Kaidou
  images/kaido.jpg
  index.html
Labels: hacktoberfest-accepted

#41 added Sakura
  images/sakura.jpg
  index.html
Labels: hacktoberfest-accepted

#42 Killua
  images/Killua.jpg
  index.html
Labels: hacktoberfest-accepted

#45 added Ken Kaneki character
  images/ken-kaneki.jpg
  index.html
Labels: hacktoberfest-accepted

#50 Added RockLee
  images/rocklee.jpg
  index.html
Labels: hacktoberfest-accepted

#55 Added Kiyotaka Ayanokoji
  images/ayanokoji.jpg
  index.html
Labels: hacktoberfest-accepted

#58 Bug Fixes
  index.html
  indexdarkmode.js
Labels: bug, hacktoberfest-accepted

#56 Added Chizuru Ichinose
  images/chizuru-ichinose.png
  index.html
Labels: hacktoberfest-accepted

#61 Fixes
  index.html
Labels: bug

#49 Added Gouenji Shuuya Card
  images/Gouenji.jpg
  index.html
Labels: Awsome, hacktoberfest-accepted

#57 Added Gohan
  images/gohan.jpg
  index.html
Labels: hacktoberfest-accepted

#44 added Mikasa Ackerman Card
  images/mikasa.jpg
  index.html
Labels: hacktoberfest-accepted

#43 Satoru Gojo
  images/Satoru_Gojo.jpg
  index.html
Labels: hacktoberfest-accepted

#51 Issue #4
  images/Piccolo.png
  index.html
Labels: hacktoberfest-accepted

#14 Added Eren Yeager card
  images/eren_yeager.png
  index.html
Labels: hacktoberfest-accepted

#62 CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, special, hacktoberfest-accepted

#64 Major fixes to index.html
  index.html
  styles.css
Labels: Awsome, bug, enhancement, hacktoberfest-accepted

#67 added Ryuk card
  images/Ryuk.jpg
  index.html
Labels: hacktoberfest-accepted

#75 Added Shikamaru Nara
  images/Shikamaru Nara.jfif
  index.html
Labels: hacktoberfest-accepted

#79 solved issue #35 - Fix the Search Bar
  searchbar.js
Labels: bug, enhancement, hacktoberfest-accepted

#74 added Hashirama Senju
  images/Hashirama Senju.jpg
  index.html
Labels: hacktoberfest-accepted

#89 Kakashi Hatake
  images/kakashihatake.jpg
  index.html
Labels: hacktoberfest-accepted

#88 added ichigo card
  images/ichigo.webp
  index.html
Labels: hacktoberfest-accepted

#86 Motoko Kusanagi
  images/motoko-kusanagi.jpg
  index.html
Labels: hacktoberfest-accepted

#82 Ash Ketchum added
  images/ash_ketchum.jpg
  index.html
Labels: good first issue, hacktoberfest-accepted

#76 Nezuko Kamado
  images/Nezuko_anime_design.webp
  index.html
Labels: hacktoberfest-accepted

#72 Minato Namikaze
  images/Minato_namikaze.jpg
  index.html
Labels: hacktoberfest-accepted

#84 Redeus Greyrat added
  images/RudeusGreyrat.jpg
  index.html
Labels: hacktoberfest-accepted

#71 Added Might Guy
  images/mightguy.jpg
  index.html
Labels: hacktoberfest-accepted

#53 title : added information about Hinata
  images/hinata.jpg
  index.html
Labels: hacktoberfest-accepted

#48 Aisaka Taiga
  images/aisakataiga.jpg
  index.html
Labels: hacktoberfest-accepted

#70 Added cell (DBZ)
  images/cell.png
  index.html
Labels: hacktoberfest-accepted

#91 added Monkey D. Luffy
  images/3437a2c17ac6e710f946908182ea7100.jpg
  index.html
Labels: hacktoberfest-accepted

#92 Temari
  images/temari.jpg
  index.html
Labels: hacktoberfest-accepted

#73 issue #34 two anime characters in one line
  styles.css
Labels: hacktoberfest-accepted

#93 Major fixes in index.html
  index.html
  indexdarkmode.js
Labels: hacktoberfest-accepted

#94 Removed Light (Death Note)
  index.html
Labels: bug, hacktoberfest-accepted

#95 Zenitsu
  images/zenitsu.jpg
  index.html
Labels: hacktoberfest-accepted

#96 Revert "issue #34 two anime characters in one line"
  styles.css
Labels: enhancement, hacktoberfest-accepted

#102 jiraiya added
  images/Jiraiya.webp
  index.html
Labels: hacktoberfest-accepted

#100 Added Jiraiya
  images/jiraiya.jpg
  index.html
Labels: hacktoberfest-accepted

#97 Yor Forger
  images/yor.jpg
  index.html
Labels: hacktoberfest-accepted

#101 Adding Rui Tachibana and Solving conflict problem with 'hinata' card
  images/rui_tachibana.jpg
  index.html
Labels: hacktoberfest-accepted

#104 Added Pain card
  images/pain.jfif
  index.html
Labels: hacktoberfest-accepted

#105 Added Blast
  images/blast.jpg
  images/garou.jpeg
  index.html
Labels: hacktoberfest-accepted

#110 Added Tsunade Senju
  images/Lady Tsunade.jpg
  index.html
Labels: hacktoberfest-accepted

#109 Added card for Kankichi Ryotsu
  images/ryotsu.jpg
  index.html
Labels: hacktoberfest-accepted

#108 Added Garou
  images/tatsumaki.jpg
  index.html
Labels: hacktoberfest-accepted

#107 Update index.html
  index.html
Labels: hacktoberfest-accepted

#112 MewTwo
  CODE_OF_CONDUCT.md
  images/220px-Baron_Ash.webp
  images/3437a2c17ac6e710f946908182ea7100.jpg
  images/Gouenji.jpg
  images/Hashirama Senju.jpg
  images/Izuku_Midoriya_Action_2.webp
  images/Jiraiya.webp
  images/Katsuki_Bakugo.webp
  images/Lady Tsunade.jpg
  images/Manga_character_icon_Near.webp
  images/Minato_namikaze.jpg
  images/Nezuko_anime_design.webp
  images/Piccolo.png
  images/RudeusGreyrat.jpg
  images/Ryuk.jpg
  images/Satoru_Gojo.jpg
  images/Shikamaru Nara.jfif
  images/Sstrunks4.webp
  images/aisakataiga.jpg
  images/ash_ketchum.jpg
  images/blast.jpg
  images/cell.png
  images/eren_yeager.png
  images/garou.jpeg
  images/gohan.jpg
  images/hinata.jpg
  images/ichigo.webp
  images/jiraiya.jpg
  images/jotaro.jpg
  images/kakashihatake.jpg
  images/main-qimg-a1020396115c87011103b1b198d7d76b-lq.jpg
  images/mightguy.jpg
  images/mikasa.jpg
  images/motoko-kusanagi.jpg
  images/pain.jfif
  images/rui_tachibana.jpg
  images/ryotsu.jpg
  images/tatsumaki.jpg
  images/temari.jpg
  images/tienshinhan.jpg
  images/yor.jpg
  images/zenitsu.jpg
  index.html
  indexdarkmode.js
  searchbar.js
  styles.css
Labels: hacktoberfest-accepted

#111 Added Levi Ackerman card
  images/levi.jpg
  index.html
Labels: hacktoberfest-accepted

#118 Card updated
  index.html
Labels: hacktoberfest-accepted

#116 Add files via upload
  images/Sonoko_Suzuki.jpg
  index.html
Labels: hacktoberfest-accepted

#114 Added Tatsumaki
  index.html
Labels: hacktoberfest-accepted

#119 Senku Ishigami from DrStone is added
  index.html
Labels: hacktoberfest-accepted

#120 fixed the website
  index.html
Labels: hacktoberfest-accepted

#113 new character added Rintaro Okabe
  images/Kakashi.webp
  images/Rintarou_Okabe.webp
  index.html
Labels: hacktoberfest-accepted

#122 updated index.html with minor fixes
  index.html
Labels: bug, hacktoberfest-accepted

#130 Lupin
  images/15-lupiniii-1660778366362.jpg
  index.html
Labels: hacktoberfest-accepted

#129 Added sanji character
  index.html
  sanji.jpg
Labels: hacktoberfest-accepted

#128 Edogawa Conan
  images/detective_conan.jpg
  index.html
Labels: hacktoberfest-accepted

#126 Anthy himemiya added
  images/anthy himemiya.png
  index.html
Labels: hacktoberfest-accepted

#125 add natsuo to character card, no conflict
  images/natsuo.jpg
  index.html
Labels: hacktoberfest-accepted

#121 added rintao okabe card
  images/Okabe.Rintarou.600.1024364.jpg
  index.html
Labels: hacktoberfest-accepted

#131 Added Shinei Nouzen card
  images/ShineiNouzen.jpg
  index.html
Labels: hacktoberfest-accepted

#134 Dark mode added !
  images/sanji.jpg
  index.html
  styles.css
Labels: good first issue, hacktoberfest-accepted

#139 Added Muzan Kibutsuji
  index.html
  muzan.webp
Labels: good first issue, hacktoberfest-accepted

#132 Edward Elric added
  images/edward-elric.webp
  images/saitama.webp
  index.html
Labels: hacktoberfest-accepted

#141 Added Clare card
  images/Clare.png
  index.html
Labels: hacktoberfest-accepted

#144 CREATED AKUTO-SAI CARD
  images/akuto-sai-1.jpg
  index.html
Labels: hacktoberfest-accepted

#143 Added Genos
  index.html
Labels: hacktoberfest-accepted

#136 Sōma Yukihira
  images/Schneizel.webp
  images/soma_jpeg.jpeg
  index.html
Labels: hacktoberfest-accepted

#137 Added Touma Kamijou
  images/touma.jpg
  index.html
Labels: hacktoberfest-accepted

#106 Monster and Trigun anime added
  images/Trigun.jpg
  images/monster.jpeg
  images/sainik.jpeg
  index.html
Labels: hacktoberfest-accepted

#146 added brock
  brock.png
  index.html
Labels: hacktoberfest-accepted

#150 fixed characters & images on the site
  images/genos.webp
  images/muzan.webp
  index.html
Labels: hacktoberfest-accepted

#151 Added Sukuna
  images/sukuna.jpg
  index.html
Labels: hacktoberfest-accepted

#153 added shinobu card
  images/shinobu.jpg
  index.html
Labels: Awsome, hacktoberfest-accepted

#154 added hana ichijo card
  images/hana.jpg
  index.html
Labels: hacktoberfest-accepted

#155 added kei
  images/kei.jpg
  index.html
Labels: hacktoberfest-accepted

#156 added tengen uzui
  images/tengen.jpg
  index.html
Labels: Awsome, enhancement, hacktoberfest-accepted

#165 a
  images/Boruto.webp
  index.html
Labels: hacktoberfest-accepted

#158 Added Gyomei
  images/Gyomei_anime.webp
  index.html
Labels: hacktoberfest-accepted

#167 formatted index.html
  index.html
Labels: bug, hacktoberfest-accepted

#163 Update search-bar styling
  styles.css
Labels: bug, good first issue, hacktoberfest-accepted

#168 Sanemi added
  images/Sanemi_anime.webp
  index.html
Labels: hacktoberfest

#170 added anya forger
  images/anya.webp
  index.html
Labels: hacktoberfest-accepted

#166 Added Akane Tsunemori from Psycho Pass
  images/Psycho Pass.jpg
  index.html
Labels: hacktoberfest-accepted

#174 Shoto Todoroki Card Added
  images/Episode_23.webp
  index.html
Labels: hacktoberfest-accepted

#176 Fixed card alignment
  index.html
Labels: hacktoberfest-accepted

#182 Added Asta
  images/asta.jpeg
  index.html
Labels: hacktoberfest-accepted

#179 Changes text colour to white in dark mode
  index.html
Labels: hacktoberfest-accepted

#169 #4: Add 2B from Nier: Automata
  images/2b.png
  index.html
Labels: hacktoberfest-accepted

#157 Issue #142 Resolved , Changed font color in Light and Dark mode
  index.html
  styles.css
Labels: Awsome, enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#123 Orochimaru Added with Image
  images/Orochimaru.jpg
  index.html
Labels: hacktoberfest-accepted

#133 Added Light Yagami
  images/Light-Yagami.jpg
  images/chota-bheem.webp
  images/chota_bheem.webp
  index.html
Labels: hacktoberfest-accepted

#194 Adding Yuuto Kiba
  images/Yuuto Kiba.jpg
  index.html
Labels: good first issue, hacktoberfest-accepted

#195 Added Baki Hanma
  images/baki.jpg
  index.html
Labels: good first issue, hacktoberfest-accepted

#197 added Issei Hyoudou
  images/issei.jpg
  index.html
Labels: good first issue, hacktoberfest-accepted

#198 Adding Doraemon
  images/Doraemon.webp
  index.html
Labels: good first issue, hacktoberfest-accepted

#201 Added Claude "King Claude" Jeanne Elmir
  images/claude-jeanne.jpeg
Labels: hacktoberfest-accepted

#148 Added Guts
  images/Guts.png
  index.html
Labels: good first issue, hacktoberfest-accepted

#202 added in Pikachu
  images/pikachu.jpg
  index.html
Labels: good first issue, hacktoberfest-accepted

#199 added Yuta Okkotsu
  images/Yuta.webp
  index.html
Labels: hacktoberfest-accepted

#216 Added a character Gingka Hagane
  images/Gingka.jpg
  index.html
Labels: hacktoberfest-accepted

#218 Alignment issue fixed
  index.html
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#215 Added Hyakkimaru from Dororo
  images/Hyakkimaru.jpg
  index.html
Labels: hacktoberfest-accepted

#222 Inosuke
  images/Inosuke.jpg
  index.html
Labels: hacktoberfest-accepted

#214 title: Jolyne Cujoh
  images/jolyne_cujoh.webp
  index.html
Labels: hacktoberfest-accepted

#205 Design Guide
  CONTRIBUTING.md
  DESIGNGUIDE.md
  images/Design Guide - Dark Mode.jpg
  images/Design Guide - Light Mode.jpg
Labels: enhancement, hacktoberfest-accepted

#223 Shota Aizawa
  images/Shota.webp
  index.html
Labels: hacktoberfest-accepted

#203 Added Tenzo Kenma
  images/Tenma.webp
  index.html
Labels: hacktoberfest-accepted

#192 Armin Arlert
  images/Armin_Arlelt__Anime__character_image.jpg
  index.html
Labels: hacktoberfest-accepted

#226 Footer issue and card placement fixed
  index.html
Labels: hacktoberfest-accepted

#230 Rimuru Tempest added
  images/Rimuru_Tempest.jpeg
  index.html
Labels: hacktoberfest-accepted

#229 Added Kirito Card
  images/Kirito.png
  index.html
Labels: hacktoberfest-accepted

#232 Anos Voldigoad added
  images/Anos_Voldigoad.jpg
  index.html
Labels: hacktoberfest-accepted

#234 Veldora Tempest added
  images/Kanon.jpg
  images/Veldora_Tempest.jpg
  index.html
Labels: hacktoberfest-accepted

#235 Added Doma
  images/Demon Slayer.jpg
  index.html
Labels: hacktoberfest-accepted

#236 Velgrynd added
  images/Velgrynd.jpg
  index.html
Labels: hacktoberfest-accepted

#238 Search Suggestion for search bar Added
  index.html
  searchbar.js
  searchresults.js
  styles.css
Labels: enhancement, hacktoberfest-accepted

#243 Adding Ninja Hattori
  images/Ninja.jpg
  index.html
Labels: good first issue, hacktoberfest-accepted

#244 Added Tobio Kageyama (Haikyuu) card
  Tobio Kageyama (Haikyuu).webp
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#256 Master Roshi Added
  images/master-roshi.png
  index.html
Labels: hacktoberfest-accepted

#255 added boros
  images/boros.jpg
  index.html
Labels: hacktoberfest-accepted

#252 Added Agni card
  images/Agni.png
  index.html
Labels: hacktoberfest-accepted

#257 adding one piece character
  images/tony_tony_chopper.webp
  index.html
Labels: hacktoberfest-accepted

#251 yamato
  images/yamato.jpg
  index.html
Labels: hacktoberfest-accepted

#246 Added Hinata Shoyo card
  images/shoyo_hinata.jpg
  index.html
Labels: hacktoberfest-accepted

#227 Added Katara Card
  images/Katara.webp
  index.html
Labels: hacktoberfest-accepted

#237 Add Dazai Card
  images/Osamu_Dazai.webp
  index.html
Labels: hacktoberfest-accepted

#240 Added Neji Hyuga from Naruto
  images/Naruto Negi.jpg
  index.html
Labels: hacktoberfest-accepted

#266 Added Hitagi Senjougahara card
  images/Hitagi Senjougahara.png
  index.html
Labels: hacktoberfest-accepted

#265 Added Violet evergarden
  images/Violet-Evergarden.jpeg
  index.html
Labels: hacktoberfest-accepted

#263 Add new character hxh, Gon, by Jackson Roberio
  images/gon-hxh.jpg
  index.html
Labels: hacktoberfest-accepted

#260 Added new Character (Denji from ChainsawMan)
  images/Denji.webp
  index.html
Labels: hacktoberfest-accepted

#261 Corrections in previous card and added a card
  images/nico_robin.jpg
  index.html
Labels: hacktoberfest-accepted

#250 mobile device changes
  index.html
  styles.css
Labels: enhancement, special, hacktoberfest, hacktoberfest-accepted

#275 Added Gon Freecss card
  images/Gon Freecss.png
  index.html
Labels: hacktoberfest-accepted
